#ifndef UT_RLUWIN_H
#define UT_RLUWIN_H

#include "PlatformDetection.h"

#ifdef RL_PLATFORM_WINDOWS
	#include <sdkddkver.h>

	#define NOGDICAPMASKS
	#define NOVIRTUALKEYCODES
	#define NOWINMESSAGES
	#define NOWINSTYLES
	#define NOSYSMETRICS
	#define NOMENUS
	#define NOICONS
	#define NOKEYSTATES
	#define NOSYSCOMMANDS
	#define NORASTEROPS
	#define NOSHOWWINDOW
	#define OEMRESOURCE
	#define NOATOM
	#define NOCLIPBOARD
	#define NOCOLOR
	#define NOCTLMGR
	#define NODRAWTEXT
	#define NOGDI
	#define NOKERNEL
	#define NOUSER
	#define NOMB
	#define NOMEMMGR
	#define NOMETAFILE
	#define NOMINMAX
	#define NOMSG
	#define NOOPENFILE
	#define NOSCROLL
	#define NOSERVICE
	#define NOSOUND
	#define NOTEXTMETRIC
	#define NOWH
	#define NOWINOFFSETS
	#define NOCOMM
	#define NOKANJI
	#define NOHELP
	#define NOPROFILER
	#define NODEFERWINDOWPOS
	#define NOMCX
	
	#include <Windows.h>
	
	#undef NOGDICAPMASKS
	#undef NOVIRTUALKEYCODES
	#undef NOWINMESSAGES
	#undef NOWINSTYLES
	#undef NOSYSMETRICS
	#undef NOMENUS
	#undef NOICONS
	#undef NOKEYSTATES
	#undef NOSYSCOMMANDS
	#undef NORASTEROPS
	#undef NOSHOWWINDOW
	#undef OEMRESOURCE
	#undef NOATOM
	#undef NOCLIPBOARD
	#undef NOCOLOR
	#undef NOCTLMGR
	#undef NODRAWTEXT
	#undef NOGDI
	#undef NOKERNEL
	#undef NOUSER
	#undef NOMB
	#undef NOMEMMGR
	#undef NOMETAFILE
	#undef NOMINMAX
	#undef NOMSG
	#undef NOOPENFILE
	#undef NOSCROLL
	#undef NOSERVICE
	#undef NOSOUND
	#undef NOTEXTMETRIC
	#undef NOWH
	#undef NOWINOFFSETS
	#undef NOCOMM
	#undef NOKANJI
	#undef NOHELP
	#undef NOPROFILER
	#undef NODEFERWINDOWPOS
	#undef NOMCX
#endif // RL_PLATFORM_WINDOWS

#endif